name: Fontend Docker HUB
on:
  push:
    branches: [ main ]
jobs:
  dockerPublish:
    name: Building and publishing image docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build production
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: setup docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          file: ./Dockerfile
          tags: codingandshare/tracking-issue-ui:latest
      - run: docker push codingandshare/tracking-issue-ui:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

