name: FrontEnd CI with NodeJS
on:
  pull_request:
jobs:
  test:
    name: Build production mode
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build production
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
